export const VUE_COMPONENT_FIXTURES = [
  'Attrs.vue',
  'Basic.vue',
  'BasicFormat.vue',
  'Exist.vue',
  'External.vue',
  'Force.vue',
  'Functional.vue',
  'FunctionalLangFill.vue',
  'HasNested.vue',
  'LangContentMissmatch.vue',
  'Multi.vue',
  'MultiFormat.vue',
  'NoBlock.vue',
  'Oneline.vue',
  'OptionLangContentMissmatch.vue',
  'Unknown.vue',
  'Yaml.vue'
]
